import { useMemo, useState } from 'react';
import { Check, CheckSquare, Clipboard, Download, FileText, Square, X } from 'lucide-react';
import type { Source } from '../api/types';
import { Modal } from './ui';
import AnimatedInput from './premium/AnimatedInput';
import GlowingIcon from './premium/GlowingIcon';
import PremiumButton from './premium/PremiumButton';
import { relevancePercent } from '../utils/relevance';
import { downloadBlob } from '../utils/download';

export interface ReportBuilderWizardProps {
  open: boolean;
  onClose: () => void;
  sources: readonly Source[];
}

type WizardStep = 1 | 2 | 3;

interface ReportOptions {
  includeFullChunks: boolean;
  includeScores: boolean;
  includeMetadata: boolean;
}

const STEPS: Array<{ number: WizardStep; label: string; description: string }> = [
  { number: 1, label: 'Select', description: 'Choose evidence' },
  { number: 2, label: 'Configure', description: 'Set report options' },
  { number: 3, label: 'Generate', description: 'Review and export' },
];

function classes(...values: Array<string | false | undefined>): string {
  return values.filter(Boolean).join(' ');
}

function sourceKey(source: Source, index: number): string {
  return source.chunk_id || `${source.document_id}-${index}`;
}

function sourceName(source: Source): string {
  return source.document_name || `Document ${source.document_id.slice(0, 8)}`;
}

function snippet(text: string, maximumLength = 280): string {
  const trimmed = text.trim();
  return trimmed.length > maximumLength ? `${trimmed.slice(0, maximumLength).trimEnd()}…` : trimmed;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function quoteMarkdown(value: string): string {
  const text = value.trim() || 'No cited passage was returned for this source.';
  return text.split('\n').map((line) => `> ${line}`).join('\n');
}

function formatOptionalScore(score: number | undefined): string | null {
  if (score == null || !Number.isFinite(score)) return null;
  return score >= 0 && score <= 1 ? `${(score * 100).toFixed(0)}%` : score.toFixed(2);
}

function buildMarkdown(title: string, sources: readonly Source[], options: ReportOptions): string {
  const selectedSources = sources;
  const lines = [
    `# ${title.trim()}`,
    '',
    '> Evidence package generated by TruthLens AI. Validate cited passages against their source documents before relying on this report.',
    '',
    `**Evidence included:** ${selectedSources.length}`,
    `**Generated:** ${new Date().toLocaleString()}`,
    '',
  ];

  if (selectedSources.length >= 5) {
    lines.push('## Table of Contents', '');
    selectedSources.forEach((source, index) => {
      const number = index + 1;
      const name = sourceName(source);
      lines.push(`- [Source ${number}: ${name}](#source-${number}-${slugify(name)})`);
    });
    lines.push('');
  }

  lines.push('## Evidence', '');
  selectedSources.forEach((source, index) => {
    const number = index + 1;
    const name = sourceName(source);
    const sourceText = options.includeFullChunks ? source.excerpt : snippet(source.excerpt);

    lines.push(`### Source ${number}: ${name}`, '');
    if (options.includeMetadata) {
      lines.push(`- **Document:** ${name}`, `- **Chunk:** ${source.chunk_id || 'Unavailable'}`);
      if (source.page_number != null) lines.push(`- **Page:** ${source.page_number}`);
      if (source.file_type) lines.push(`- **File type:** ${source.file_type}`);
      if (source.updated_at) lines.push(`- **Last updated:** ${source.updated_at}`);
    }
    if (options.includeScores) {
      lines.push(`- **Relevance:** ${relevancePercent(source.relevance_score)}%`);
      const confidence = formatOptionalScore(source.confidence);
      const rerank = formatOptionalScore(source.rerank_score);
      if (confidence) lines.push(`- **Confidence:** ${confidence}`);
      if (rerank) lines.push(`- **Rerank score:** ${rerank}`);
    }
    if (options.includeMetadata || options.includeScores) lines.push('');
    lines.push(quoteMarkdown(sourceText), '', `[^${number}]`, '');
  });

  lines.push('## Citations', '');
  selectedSources.forEach((source, index) => {
    const number = index + 1;
    const location = source.page_number != null ? `, p. ${source.page_number}` : '';
    lines.push(`[^${number}]: ${sourceName(source)}${location}. Chunk: ${source.chunk_id || 'Unavailable'}.`);
  });

  return lines.join('\n');
}

function OptionToggle({ checked, onChange, title, description }: { checked: boolean; onChange: (checked: boolean) => void; title: string; description: string }) {
  return (
    <button
      type="button"
      aria-pressed={checked}
      onClick={() => onChange(!checked)}
      className={classes('flex w-full items-start gap-3 rounded-xl border p-3 text-left transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50', checked ? 'border-primary/40 bg-primary/10' : 'border-glass-border bg-white/[0.025] hover:border-primary/25')}
    >
      <span className={classes('mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border', checked ? 'border-primary/60 bg-primary text-bg' : 'border-border bg-bg-soft text-transparent')}>
        <Check size={13} strokeWidth={3} aria-hidden="true" />
      </span>
      <span><span className="block text-sm font-medium text-text">{title}</span><span className="mt-0.5 block text-xs leading-relaxed text-text-dim">{description}</span></span>
    </button>
  );
}

function StepIndicator({ currentStep, onStepChange }: { currentStep: WizardStep; onStepChange: (step: WizardStep) => void }) {
  return (
    <ol className="grid grid-cols-3 gap-2" aria-label="Report builder steps">
      {STEPS.map((step) => {
        const active = step.number === currentStep;
        const complete = step.number < currentStep;
        const reachable = step.number < currentStep;
        return (
          <li key={step.number}>
            <button
              type="button"
              disabled={!reachable && !active}
              onClick={() => onStepChange(step.number)}
              aria-current={active ? 'step' : undefined}
              className={classes('flex w-full items-center gap-2 rounded-xl border px-2.5 py-2 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 disabled:cursor-not-allowed', active ? 'border-primary/40 bg-primary/10 text-primary-soft' : complete ? 'border-accent/30 bg-accent/10 text-accent hover:border-accent/50' : 'border-glass-border bg-white/[0.02] text-text-dim')}
            >
              <span className={classes('flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[11px] font-bold', active ? 'bg-primary text-bg' : complete ? 'bg-accent text-bg' : 'bg-card-2 text-text-dim')}>{complete ? <Check size={12} strokeWidth={3} aria-hidden="true" /> : step.number}</span>
              <span className="min-w-0"><span className="block truncate text-xs font-semibold">{step.label}</span><span className="hidden truncate text-[10px] opacity-75 sm:block">{step.description}</span></span>
            </button>
          </li>
        );
      })}
    </ol>
  );
}

/** Premium, in-session evidence selection and export workflow. */
export function ReportBuilderWizard({ open, onClose, sources }: ReportBuilderWizardProps) {
  const [step, setStep] = useState<WizardStep>(1);
  const [selectedSourceKeys, setSelectedSourceKeys] = useState<Set<string>>(() => new Set());
  const [title, setTitle] = useState('Evidence Package');
  const [options, setOptions] = useState<ReportOptions>({ includeFullChunks: false, includeScores: true, includeMetadata: true });
  const [generated, setGenerated] = useState(false);
  const [copyStatus, setCopyStatus] = useState<string | null>(null);

  const selectedSources = useMemo(
    () => sources.filter((source, index) => selectedSourceKeys.has(sourceKey(source, index))),
    [selectedSourceKeys, sources],
  );
  const markdown = useMemo(() => buildMarkdown(title, selectedSources, options), [options, selectedSources, title]);
  const selectionError = selectedSources.length === 0 ? 'Select at least one source to build an evidence package.' : null;
  const titleError = title.trim() ? undefined : 'A report title is required.';
  const canGenerate = !selectionError && !titleError;
  const allSelected = sources.length > 0 && selectedSources.length === sources.length;

  const updateTitle = (value: string) => {
    setTitle(value);
    setGenerated(false);
    setCopyStatus(null);
  };

  const toggleSource = (source: Source, index: number) => {
    const key = sourceKey(source, index);
    setSelectedSourceKeys((previous) => {
      const next = new Set(previous);
      if (next.has(key)) next.delete(key); else next.add(key);
      return next;
    });
    setGenerated(false);
    setCopyStatus(null);
  };

  const toggleAll = () => {
    setSelectedSourceKeys(allSelected ? new Set() : new Set(sources.map(sourceKey)));
    setGenerated(false);
    setCopyStatus(null);
  };

  const goNext = () => {
    if (step === 1 && selectionError) return;
    if (step === 2 && titleError) return;
    setStep(step === 1 ? 2 : 3);
  };

  const downloadReport = () => {
    if (!canGenerate) return;
    downloadBlob(
      new Blob([markdown], { type: 'text/markdown;charset=utf-8' }),
      `${slugify(title) || 'evidence-package'}.md`,
    );
    setGenerated(true);
    setCopyStatus(null);
  };

  const copyMarkdown = async () => {
    if (!canGenerate) return;
    try {
      await navigator.clipboard.writeText(markdown);
      setCopyStatus('Markdown copied to clipboard.');
    } catch {
      setCopyStatus('Could not copy Markdown. Check browser permissions.');
    }
  };

  return (
    <Modal open={open} onClose={onClose} title="Report Builder" className="max-w-4xl">
      <div className="max-h-[calc(100vh-11rem)] space-y-5 overflow-y-auto pr-1">
        <StepIndicator currentStep={step} onStepChange={setStep} />

        {step === 1 && (
          <section aria-labelledby="report-select-heading">
            <div className="flex flex-col gap-2 border-b border-glass-border pb-3 sm:flex-row sm:items-end sm:justify-between">
              <div><h3 id="report-select-heading" className="text-base font-semibold text-text">Select evidence</h3><p className="mt-1 text-xs text-text-dim">Choose the cited passages to include in this evidence package.</p></div>
              <div className="flex items-center gap-2"><span className="text-xs font-medium text-primary-soft">{selectedSources.length} of {sources.length} selected</span><button type="button" onClick={toggleAll} className="inline-flex items-center gap-1 rounded-lg border border-border bg-bg-soft px-2.5 py-1.5 text-xs font-medium text-text-muted transition-colors hover:border-primary/30 hover:text-primary-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50">{allSelected ? <Square size={13} aria-hidden="true" /> : <CheckSquare size={13} aria-hidden="true" />}{allSelected ? 'Deselect all' : 'Select all'}</button></div>
            </div>
            {selectionError && <p className="mt-3 flex items-center gap-1.5 text-xs text-red"><X size={13} aria-hidden="true" />{selectionError}</p>}
            {sources.length === 0 ? <p className="mt-4 rounded-xl border border-border bg-bg-soft p-4 text-sm text-text-muted">No evidence sources are available for this report.</p> : (
              <div className="mt-3 max-h-[22rem] space-y-2 overflow-y-auto pr-1">
                {sources.map((source, index) => {
                  const key = sourceKey(source, index);
                  const selected = selectedSourceKeys.has(key);
                  const confidence = formatOptionalScore(source.confidence);
                  return <label key={key} className={classes('flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition-colors', selected ? 'border-primary/40 bg-primary/10' : 'border-glass-border bg-white/[0.02] hover:border-primary/25')}>
                    <input type="checkbox" checked={selected} onChange={() => toggleSource(source, index)} className="mt-1 h-4 w-4 shrink-0 accent-primary" />
                    <span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="max-w-full truncate text-sm font-medium text-text" title={sourceName(source)}>{sourceName(source)}</span><span className="font-mono text-[10px] text-text-dim">{source.chunk_id}</span></span><span className="mt-1 block text-xs leading-relaxed text-text-muted">{snippet(source.excerpt, 180) || 'No passage preview was returned.'}</span><span className="mt-2 flex flex-wrap gap-2 text-[11px] text-text-dim"><span>Relevance {relevancePercent(source.relevance_score)}%</span>{confidence && <span>Confidence {confidence}</span>}{source.page_number != null && <span>p. {source.page_number}</span>}</span></span>
                  </label>;
                })}
              </div>
            )}
          </section>
        )}

        {step === 2 && (
          <section aria-labelledby="report-configure-heading" className="space-y-4">
            <div><h3 id="report-configure-heading" className="text-base font-semibold text-text">Configure package</h3><p className="mt-1 text-xs text-text-dim">Set the report identity and evidence detail level.</p></div>
            <AnimatedInput label="Report title" value={title} onChange={(event) => updateTitle(event.target.value)} error={titleError} icon={<FileText size={16} />} placeholder="e.g. Q3 Procurement Evidence Package" />
            <div className="space-y-2">
              <OptionToggle checked={options.includeFullChunks} onChange={(checked) => { setOptions((previous) => ({ ...previous, includeFullChunks: checked })); setGenerated(false); }} title="Full cited chunk text" description="Include the full available cited passage. When off, use a concise snippet preview." />
              <OptionToggle checked={options.includeScores} onChange={(checked) => { setOptions((previous) => ({ ...previous, includeScores: checked })); setGenerated(false); }} title="Include scores" description="Add relevance, confidence, and rerank signals where the source provides them." />
              <OptionToggle checked={options.includeMetadata} onChange={(checked) => { setOptions((previous) => ({ ...previous, includeMetadata: checked })); setGenerated(false); }} title="Include source metadata" description="Add document, chunk, page, file type, and update details where available." />
            </div>
          </section>
        )}

        {step === 3 && (
          <section aria-labelledby="report-generate-heading" className="space-y-4">
            <div className="flex flex-col gap-2 border-b border-glass-border pb-3 sm:flex-row sm:items-end sm:justify-between"><div><h3 id="report-generate-heading" className="text-base font-semibold text-text">Review Markdown</h3><p className="mt-1 text-xs text-text-dim">Preview the package before downloading or copying it.</p></div><span className="text-xs font-medium text-primary-soft">{selectedSources.length} evidence sources</span></div>
            {!canGenerate && <div className="rounded-xl border border-red/30 bg-red/5 p-3 text-xs text-red">{selectionError ?? titleError}</div>}
            <pre className="max-h-[22rem] overflow-auto rounded-xl border border-glass-border bg-[#0b0f17]/80 p-4 text-xs leading-relaxed text-text-muted"><code>{markdown}</code></pre>
            <div className="flex flex-col gap-3 border-t border-glass-border pt-4 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => void copyMarkdown()} disabled={!canGenerate} className="inline-flex items-center gap-1.5 rounded-xl border border-border bg-bg-soft px-3 py-2 text-xs font-medium text-text-muted transition-colors hover:border-primary/30 hover:text-primary-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 disabled:cursor-not-allowed disabled:opacity-50"><Clipboard size={14} aria-hidden="true" />Copy Markdown</button>{copyStatus && <span className="text-xs text-text-dim" role="status">{copyStatus}</span>}</div>
              <PremiumButton type="button" onClick={downloadReport} disabled={!canGenerate} icon={<Download size={16} />} size="md">Generate Report</PremiumButton>
            </div>
            {generated && <div className="flex items-center gap-3 rounded-xl border border-accent/25 bg-accent/10 p-3"><GlowingIcon icon={<Check size={18} className="text-accent" aria-hidden="true" />} active color="#34d399" onClick={() => setGenerated(false)} ariaLabel="Dismiss report generated confirmation" /><div><p className="text-sm font-semibold text-accent">Report generated</p><p className="text-xs text-text-muted">The Markdown package was downloaded. Select the glow icon to dismiss this confirmation.</p></div></div>}
          </section>
        )}

        <div className="flex items-center justify-between border-t border-glass-border pt-4">
          <button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-xs font-medium text-text-dim transition-colors hover:bg-card-2 hover:text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50">Cancel</button>
          {step < 3 && <button type="button" onClick={goNext} disabled={step === 1 ? Boolean(selectionError) : Boolean(titleError)} className="rounded-xl border border-primary/35 bg-primary/15 px-4 py-2 text-xs font-semibold text-primary-soft transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 disabled:cursor-not-allowed disabled:opacity-50">Continue to {step === 1 ? 'configure' : 'preview'}</button>}
        </div>
      </div>
    </Modal>
  );
}

export default ReportBuilderWizard;
