import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Clock, FileText, MessageSquare, Plus, Settings } from 'lucide-react';
import { Badge, Button, Card, EmptyState, LoadingSpinner } from '../components/ui';
import { pageTransition, staggerContainer, staggerItem } from '../components/motion';
import { PageHeader, PageShell } from '../components/PageWrappers';
import { useAuth } from '../context/auth-context';
import { documentApi, queryApi } from '../api/client';
import type { QuerySummary } from '../api/types';
import { getTrustBadgeColor, getTrustColorVar, getTrustStatusLabel } from '../utils/relevance';

const RECENT_CHATS_LIMIT = 5;

const QUICK_ACTIONS = [
  { label: 'New Chat', path: '/workspaces', icon: MessageSquare },
  { label: 'Browse Documents', path: '/documents', icon: FileText },
  { label: 'View History', path: '/chats', icon: Clock },
  { label: 'Settings', path: '/settings', icon: Settings },
];

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function getGreeting(): string {
  const hour = new Date().getHours();
  if (hour < 12) return 'Good morning';
  if (hour < 17) return 'Good afternoon';
  return 'Good evening';
}

/** Human-readable name for the greeting: prefer username, fall back to the
 *  email local part, and drop any trailing autogenerated numeric id so
 *  "qau1784194002" reads as "Qau" rather than a machine handle. */
function displayName(user: { username?: string; email?: string } | null): string {
  const raw = (user?.username || user?.email?.split('@')[0] || '').trim();
  const cleaned = raw.replace(/[_-]?\d{4,}$/, '').replace(/[_-]+/g, ' ').trim() || raw;
  return cleaned ? cleaned.charAt(0).toUpperCase() + cleaned.slice(1) : '';
}

export default function UserDashboard() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [chats, setChats] = useState<QuerySummary[]>([]);
  const [totalQueries, setTotalQueries] = useState(0);
  const [totalDocs, setTotalDocs] = useState<number | null>(null);
  const [avgTrustScore, setAvgTrustScore] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      const [queriesResult, documentsResult] = await Promise.allSettled([
        queryApi.listAll({ page: 1, page_size: RECENT_CHATS_LIMIT }),
        documentApi.listAll({ page: 1, page_size: 1 }),
      ]);
      if (cancelled) return;

      if (queriesResult.status === 'fulfilled') {
        const recent = queriesResult.value.data || [];
        setChats(recent);
        setTotalQueries(queriesResult.value.meta?.total ?? recent.length);
        const scored = recent.filter((q): q is QuerySummary & { trust_score: number } => q.trust_score !== undefined);
        setAvgTrustScore(
          scored.length > 0
            ? scored.reduce((sum, q) => sum + q.trust_score, 0) / scored.length
            : null,
        );
      } else {
        setChats([]);
        setTotalQueries(0);
        setAvgTrustScore(null);
      }

      // Documents Available has no dedicated stats endpoint for regular users —
      // derive it from the real paginated total rather than faking a number.
      setTotalDocs(documentsResult.status === 'fulfilled' ? (documentsResult.value.meta?.total ?? 0) : null);

      setLoading(false);
    }

    void load();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="-mx-4 px-4 lg:-mx-6 lg:px-8 xl:px-12">
      <motion.div className="mx-auto max-w-[1200px] py-6" variants={pageTransition} initial="initial" animate="animate">
        <PageShell>
          <PageHeader
            title={displayName(user) ? `${getGreeting()}, ${displayName(user)}` : getGreeting()}
            description="Snapshot of your docs, chats, and trust signals."
            actions={(
              <Link to="/workspaces">
                <Button size="md" className="whitespace-nowrap">
                  <Plus size={16} />
                  New Chat
                </Button>
              </Link>
            )}
          />

          <motion.div className="grid gap-4 sm:grid-cols-3" variants={staggerContainer} initial="initial" animate="animate">
            {/* No per-user document-count endpoint exists — only render this card
                once the real paginated total has loaded successfully. */}
            {totalDocs !== null && (
              <motion.div variants={staggerItem}>
                <Card>
                  <p className="text-sm text-text-muted">Documents Available</p>
                  <p className="mt-1 text-2xl font-bold text-text">{loading ? '—' : totalDocs}</p>
                </Card>
              </motion.div>
            )}
            <motion.div variants={staggerItem}>
              <Card>
                <p className="text-sm text-text-muted">Recent Queries</p>
                <p className="mt-1 text-2xl font-bold text-text">{loading ? '—' : totalQueries}</p>
              </Card>
            </motion.div>
            {/* Avg Trust Score is derived from real recent-query data — hide it
                rather than show a fabricated number when nothing has been scored yet. */}
            {!loading && avgTrustScore !== null && (
              <motion.div variants={staggerItem}>
                <Card>
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-sm text-text-muted">Avg Trust Score</p>
                      <p className="mt-1 text-2xl font-bold tabular-nums" style={{ color: getTrustColorVar(avgTrustScore) }}>
                        {avgTrustScore.toFixed(2)}
                      </p>
                    </div>
                    <Badge color={getTrustBadgeColor(avgTrustScore)}>{getTrustStatusLabel(avgTrustScore)}</Badge>
                  </div>
                </Card>
              </motion.div>
            )}
          </motion.div>

          <motion.div variants={staggerItem}>
            <h2 className="mb-3 text-base font-semibold text-text">Quick Actions</h2>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {QUICK_ACTIONS.map((action) => {
                const Icon = action.icon;
                return (
                  <Link key={action.label} to={action.path}>
                    <Card hover className="p-4">
                      <div className="flex items-center gap-2 text-sm font-medium text-text">
                        <Icon size={16} className="text-primary-soft" />
                        {action.label}
                      </div>
                    </Card>
                  </Link>
                );
              })}
            </div>
          </motion.div>

          <motion.div variants={staggerItem}>
            <div className="mb-3 flex items-center justify-between">
              <h2 className="text-base font-semibold text-text">Recent Chats</h2>
              <Link to="/chats" className="text-xs text-primary-soft hover:text-primary transition-colors">
                View all
              </Link>
            </div>

            {loading ? (
              <LoadingSpinner text="Loading recent chats..." />
            ) : chats.length === 0 ? (
              <EmptyState
                icon={<MessageSquare size={24} />}
                title="No chats yet"
                description="Start conversation to see recent activity."
                action={(
                  <Link to="/workspaces">
                    <Button size="sm">
                      <MessageSquare size={14} />
                      New Chat
                    </Button>
                  </Link>
                )}
              />
            ) : (
              <div className="space-y-2">
                {chats.map((chat) => (
                  <Link key={chat.id} to={`/chat/${chat.id}`}>
                    <Card hover className="p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0 flex-1">
                          <p className="truncate text-sm text-text">{chat.query_text}</p>
                          <div className="mt-1.5 flex items-center gap-3 text-xs text-text-dim">
                            <span className="flex items-center gap-1">
                              <Clock size={11} />
                              {formatTimestamp(chat.created_at)}
                            </span>
                            {chat.model_used && <span>{chat.model_used}</span>}
                          </div>
                        </div>
                        {chat.trust_score !== undefined && (
                          <Badge color={getTrustBadgeColor(chat.trust_score)}>{chat.trust_score.toFixed(2)}</Badge>
                        )}
                      </div>
                    </Card>
                  </Link>
                ))}
              </div>
            )}
          </motion.div>
        </PageShell>
      </motion.div>
    </div>
  );
}
